### ISSUE TITLE
Please specify the version of softwares

### ISSUE THREAD

**Issue by skbhat** [mattn/webcam-detect-tflite#3]
Namaste,

Your code is the most simple version I have seen till now. But I am facing compilation issues.  Can you please specify the version of Ubuntu, tensorflow and c++ etc which resulted successful deployment.

regards
skbhat

**Comment by mattn** [comment]
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"

$ g++ (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

libtensorflow.so can be built from latest commit of tensorflow.

**Comment by skbhat** [comment]
Thanks for the update.  My aim is to port detector to RB5.  After several failures I am trying to first build it on my laptop first.  I have built libtensorflow-lite.a from the latest commit.  In the Makefile used --std=c++14.  After compilation I am getting linker error.  Some of them are strange like "undefined reference to `ruy::HaveBuiltPathForAvx2Fma()".  It is strange because I am explicitly linking libruy_have_built_path_for_avx2_fma.a.  Will keep you updated. Thanks again.

**Comment by mattn** [comment]
I fixed Makefile and main.cxx bits. please fix TENSORFLOW_ROOT for your environment in Makefile.

**Comment by skbhat** [comment]
[Makefile.txt](https://github.com/mattn/webcam-detect-tflite/files/14472776/Makefile.txt)

I have two more questions.  

1.  For me it is giving many linker errors to ruy package.  How did you manage to compile it without adding ruy libraries?
2.  Can you please let me know how did you install freetype2?

I have linked freetype2 from libs available with anaconda.  But could not resolve the following two types of linker errors

*********************************************   Type 1: Undefined references to Ruy packages **************************
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_ctx.a(ctx.cc.o): in function `std::_Function_handler<bool (), ruy::(anonymous namespace)::DetectRuntimeSupportedPaths(ruy::Path, ruy::CpuInfo*)::{lambda()#3}>::_M_invoke(std::_Any_data const&)':
ctx.cc:(.text+0x39): undefined reference to `ruy::HaveBuiltPathForAvx2Fma()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_ctx.a(ctx.cc.o): in function `std::_Function_handler<bool (), ruy::(anonymous namespace)::DetectRuntimeSupportedPaths(ruy::Path, ruy::CpuInfo*)::{lambda()#4}>::_M_invoke(std::_Any_data const&)':
ctx.cc:(.text+0x69): undefined reference to `ruy::HaveBuiltPathForAvx512()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_ctx.a(ctx.cc.o): in function `std::_Function_handler<bool (), ruy::(anonymous namespace)::DetectRuntimeSupportedPaths(ruy::Path, ruy::CpuInfo*)::{lambda()#2}>::_M_invoke(std::_Any_data const&)':
ctx.cc:(.text+0x1d): undefined reference to `ruy::CpuInfo::Avx()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_ctx.a(ctx.cc.o): in function `std::_Function_handler<bool (), ruy::(anonymous namespace)::DetectRuntimeSupportedPaths(ruy::Path, ruy::CpuInfo*)::{lambda()#3}>::_M_invoke(std::_Any_data const&)':
ctx.cc:(.text+0x4d): undefined reference to `ruy::CpuInfo::Avx2Fma()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_ctx.a(ctx.cc.o): in function `std::_Function_handler<bool (), ruy::(anonymous namespace)::DetectRuntimeSupportedPaths(ruy::Path, ruy::CpuInfo*)::{lambda()#4}>::_M_invoke(std::_Any_data const&)':
ctx.cc:(.text+0x7d): undefined reference to `ruy::CpuInfo::Avx512()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_tune.a(tune.cc.o): in function `ruy::TuningResolver::ResolveNow(ruy::CpuInfo*)':
tune.cc:(.text+0xc): undefined reference to `ruy::CpuInfo::CurrentCpuIsA55ish()'
/usr/bin/ld: tune.cc:(.text+0x21): undefined reference to `ruy::CpuInfo::CurrentCpuIsX1()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_context.a(context.cc.o): in function `ruy::Context::~Context()':
context.cc:(.text+0x143): undefined reference to `ruy::CpuInfo::~CpuInfo()'
/usr/bin/ld: context.cc:(.text+0x18e): undefined reference to `ruy::ThreadPool::~ThreadPool()'
 $TensorFlowRoot/tflitebuild/_deps/ruy-build/ruy/libruy_frontend.a(frontend.cc.o): in function `ruy::MulFrontEndFromTrMulParams(ruy::Ctx*, ruy::TrMulParams*)':
frontend.cc:(.text+0x12): undefined reference to `ruy::PreparePackedMatrices(ruy::Ctx*, ruy::TrMulParams*)'
/usr/bin/ld: frontend.cc:(.text+0x1d): undefined reference to `ruy::TrMul(ruy::Ctx*, ruy::TrMulParams*)'

*********************************************   Type 2: Undefined references to Ruy packages **************************

/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'

**Comment by mattn** [comment]
I installed freetype2 with `sudo apt install libfreetype-dev`.

>std::condition_variable::wait(std::unique_lockstd::mutex&)@GLIBCXX_3.4.30

It seems that you install non-matched library to your system.

**Comment by skbhat** [comment]
After installing freetype2, the GLIBCXX error is solved.  Only thing that remains is the errors related to ruy package.  Thanks a lot for your support.
