### ISSUE TITLE
XNNPACK delegate for CPU

### ISSUE THREAD

**Issue by skbhat** [mattn/webcam-detect-tflite#4]
Namaste,

I was able to successfully compile and run yolov5 detector with some computations delegated to GPU.  But other part is not being delegated because of following reason:

***************************************
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
.
.
.
ERROR: Following operations are not supported by GPU delegate:
DELEGATE TfLiteXNNPackDelegate: Operation is not supported.
1 operations will run on the GPU, and the remaining 4 operations will run on the CPU.
INFO: Initialized OpenCL-based API.
INFO: Created 1 GPU delegate kernels.
****************************************

If you know how to delegate XNNPACK to GPU, please provide pointers.

thanks

**Comment by mattn** [comment]
To use XNNPACK delegate, the model must be quantized to be optimized for XNNPACK.

**Comment by skbhat** [comment]
I turned off XNNPACK while compiling tensorflow.  Now I am not getting that message.  I am not sure what will be its effect on speed.
